#' WSG Drainage Closure (FWA Topology)
#'
#' Given a focal set of FWA watershed groups, return the **drainage closure**
#' — the focal groups plus every watershed group their water flows through —
#' ordered downstream-first. Pure FWA topology; no species or bundle
#' knowledge.
#'
#' Each group is represented by its outlet **point** — a
#' `blue_line_key` + `downstream_route_measure` pair with the accompanying
#' `wscode_ltree` and `localcode_ltree` — and pairs are tested with
#' `whse_basemapping.fwa_downstream()`, the same primitive family as the
#' `fwa_upstream()` used elsewhere in fresh.
#'
#' A point is required rather than a single code because a lone ltree cannot
#' order two groups that share a stem: every Fraser group carries wscode
#' `100` and five Skeena groups carry `400`. Upper Fraser and Lower Fraser
#' are separable only by measure — both sit on `blue_line_key` 356364114, at
#' 1,189,576 m and 0 m respectively.
#'
#' Order: number of groups downstream ascending, ties alphabetical, so the
#' most downstream groups come first. Running per-WSG work in this order
#' persists downstream barriers before upstream groups read them, which makes
#' cross-WSG accessibility flags settle correctly within a single pass. The
#' ordering is derived from topology, not from an ltree depth that ties
#' across a whole stem.
#'
#' @param conn A [DBI::DBIConnection-class] (e.g. from [frs_db_conn()]).
#'   Used only to evaluate `fwa_downstream()`; the outlet table itself is
#'   read from `outlets`.
#' @param watershed_group_code Character vector of focal WSG codes (e.g.
#'   `c("BULK", "MORR")`). Must be non-empty and free of `NA`. Codes are
#'   upper-cased internally. Focal codes absent from the outlet table
#'   trigger a warning and are dropped; if none match, the function errors.
#' @param outlets Data frame of watershed group outlets with columns
#'   `watershed_group_code`, `blue_line_key`, `downstream_route_measure`,
#'   `wscode_ltree`, `localcode_ltree`. Defaults to the table bundled at
#'   `system.file("extdata", "wsg_outlet.csv", package = "fresh")`,
#'   regenerated by `data-raw/wsg_outlet.R`.
#'
#' @return Character vector of WSG codes — focal plus every WSG they flow
#'   through — ordered downstream-first.
#'
#' @family wsg
#'
#' @export
#'
#' @examples
#' \dontrun{
#' conn <- frs_db_conn()
#'
#' # Skeena + Peace focal — the drainage closure, downstream-first
#' frs_wsg_drainage(conn, c("PARS", "BULK"))
#'
#' # The Morice drains through the Bulkley, not the reverse. FWA carried the
#' # "Bulkley" name down through the confluence, so the Morice — the larger
#' # flow — is filed as the tributary.
#' frs_wsg_drainage(conn, "MORR")
#'
#' DBI::dbDisconnect(conn)
#' }
frs_wsg_drainage <- function(
    conn,
    watershed_group_code,
    outlets = frs_wsg_outlets()
) {
  stopifnot(
    is.character(watershed_group_code),
    length(watershed_group_code) > 0,
    !anyNA(watershed_group_code),
    all(nzchar(watershed_group_code)),
    is.data.frame(outlets)
  )
  cols_req <- c("watershed_group_code", "blue_line_key",
                "downstream_route_measure", "wscode_ltree", "localcode_ltree")
  missing_cols <- setdiff(cols_req, names(outlets))
  if (length(missing_cols) > 0L) {
    stop("`outlets` is missing column(s): ",
         paste(missing_cols, collapse = ", "), call. = FALSE)
  }

  focal <- toupper(watershed_group_code)
  known <- setdiff(focal, outlets$watershed_group_code)
  if (length(known) > 0L) {
    warning(
      "Focal WSG code(s) not found in the outlet table (dropped from ",
      "closure): ", paste(known, collapse = ", "), call. = FALSE
    )
    focal <- setdiff(focal, known)
  }
  if (length(focal) == 0L) {
    stop("No drainage closure found — none of the focal WSG codes are ",
         "present in the outlet table.", call. = FALSE)
  }

  # Build the outlet set as a VALUES list so the function needs no table in
  # the target database — only the fwa_downstream() routine itself.
  vals <- paste(
    sprintf(
      "(%s,%s,%s,%s::ltree,%s::ltree)",
      DBI::dbQuoteLiteral(conn, outlets$watershed_group_code),
      DBI::dbQuoteLiteral(conn, as.integer(outlets$blue_line_key)),
      DBI::dbQuoteLiteral(conn, as.numeric(outlets$downstream_route_measure)),
      DBI::dbQuoteLiteral(conn, as.character(outlets$wscode_ltree)),
      DBI::dbQuoteLiteral(conn, as.character(outlets$localcode_ltree))
    ),
    collapse = ", "
  )
  focal_lit <- paste(DBI::dbQuoteLiteral(conn, focal), collapse = ", ")

  # fwa_downstream() is strict — a group is not downstream of itself — so the
  # focal set is unioned in explicitly. `depth` counts how many groups each
  # closure member drains through, which orders by real topology.
  sql <- sprintf(
    paste0(
      "WITH t(wsg, blk, drm, ws, lc) AS (VALUES %s),\n",
      "f AS (SELECT * FROM t WHERE wsg IN (%s)),\n",
      "closure AS (\n",
      "  SELECT wsg FROM f\n",
      "  UNION\n",
      "  SELECT b.wsg FROM f JOIN t b ON b.wsg <> f.wsg\n",
      "  WHERE whse_basemapping.fwa_downstream(\n",
      "          f.blk, f.drm, f.ws, f.lc, b.blk, b.drm, b.ws, b.lc)\n",
      ")\n",
      "SELECT c.wsg,\n",
      "       (SELECT count(*) FROM t d WHERE d.wsg <> c.wsg\n",
      "          AND whse_basemapping.fwa_downstream(\n",
      "                ct.blk, ct.drm, ct.ws, ct.lc,\n",
      "                d.blk, d.drm, d.ws, d.lc)) AS depth\n",
      "FROM closure c JOIN t ct ON ct.wsg = c.wsg\n",
      "ORDER BY depth ASC, c.wsg ASC"
    ),
    vals, focal_lit
  )
  DBI::dbGetQuery(conn, sql)$wsg
}

#' FWA Watershed Group Outlets
#'
#' Read the bundled per-watershed-group outlet table: one row per FWA
#' watershed group giving the outlet `blue_line_key` +
#' `downstream_route_measure` and its `wscode_ltree` / `localcode_ltree`.
#' Regenerate with `data-raw/wsg_outlet.R`.
#'
#' @return Data frame with columns `watershed_group_code`, `blue_line_key`,
#'   `downstream_route_measure`, `wscode_ltree`, `localcode_ltree`.
#'
#' @family wsg
#'
#' @export
#'
#' @examples
#' head(frs_wsg_outlets())
frs_wsg_outlets <- function() {
  path <- system.file("extdata", "wsg_outlet.csv", package = "fresh")
  if (!nzchar(path)) {
    stop("Bundled wsg_outlet.csv not found in the installed fresh package.",
         call. = FALSE)
  }
  utils::read.csv(path, stringsAsFactors = FALSE, colClasses = c(
    watershed_group_code = "character",
    blue_line_key = "integer",
    downstream_route_measure = "numeric",
    wscode_ltree = "character",
    localcode_ltree = "character"
  ))
}
